### ISSUE TITLE
Maturing Bob

### ISSUE THREAD

**Issue by queengooborg** [mdn/bob#881]
This issue is a tracking issue to track the updates I am working on for Bob to help improve its codebase.  This project includes the following:

- [x] Enforce formatting with Prettier #866
- [x] Improve UX for tabbed editor #865
- [x] Drop Node.js ≤v15 support #882
- [x] Convert to ESM #880
- [x] Use ES6-level features (let/const, async/await, arrow functions, etc.) #918
- [x] Replace saved libraries with NPM packages #871 / #879
- [x] Replace Browserify with Webpack #867 / #871 / #889 / #907
- [x] Replace Prism with CodeMirror to remove extra dependency #888
- [x] Upgrade CodeMirror to v6 (see #851) #907
- [x] Fix formatting/linting #959
- [x] Add height data #839
- [x] Release Bob with new NPM package name (see #515)
